version: '2'
services:
  rpgffi10:
    environment:
      - PATH=$PATH:/root/.cargo/bin
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PG_VER=10
        - RUST_VER=1.33.0
    volumes:
      - .:/source
    working_dir: /source
    command: >
      sh -c "util/generate_bindings &&
             cargo test --verbose"
  rpgffi96:
    extends:
      service: rpgffi10
    build:
      args:
        - PG_VER=9.6
  rpgffi95:
    extends:
      service: rpgffi10
    build:
      args:
        - PG_VER=9.5
  rpgffi94:
    extends:
      service: rpgffi10
    build:
      args:
        - PG_VER=9.4
  rpgffi93:
    extends:
      service: rpgffi10
    build:
      args:
        - PG_VER=9.3
